name: Vue.js Frontend CI

on: [push, pull_request]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    
    # Build Vue.js
    - name: Build frontend
      run: |
        cd frontend
        npm install
        npm run build

    # Docker build/push
    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}
    
    - name: Build and push frontend image
      uses: docker/build-push-action@v5
      with:
        context: ./frontend
        push: ${{ github.event_name != 'pull_request' }}
        tags: |
          ${{ secrets.DOCKER_HUB_USERNAME }}/finch-frontend:latest
          ${{ secrets.DOCKER_HUB_USERNAME }}/finch-frontend:${{ github.sha }}
